// Text
export const SET_ACTIVE_WORD_INDEX = 'SET_ACTIVE_WORD_INDEX';
export const TOGGLE_TYPING = 'TOGGLE_TYPING';

// Users
export const NEW_USER_CONNECTED = 'NEW_USER_CONNECTED';
export const NEW_SEARCH_USER = 'NEW_SEARCH_USER';
export const SEARCH_ROOM_CHANGED = 'SEARCH_ROOM_CHANGED';
export const START_TYPE_FROM_SERVER = 'START_TYPE_FROM_SERVER';

// Calculations
export const SET_TIME_PASSED = 'SET_TIME_PASSED';


