export const SET_ACTIVE_WORD_INDEX = 'SET_ACTIVE_WORD_INDEX';
export const START_TYPER = 'START_TYPER';
export const SET_TIME_PASSED = 'SET_TIME_PASSED';

export const NEW_USER_CONNECTED = 'NEW_USER_CONNECTED';
